controllers/auth.py
from logging import getLogger

from flask import Blueprint, request, flash, redirect, render_template, url_for, session
from flask_login import login_user, logout_user
from werkzeug.security import check_password_hash

from models import User

auth_blueprint = Blueprint("auth", __name__, url_prefix="/auth")

_logger = getLogger(__name__)


@auth_blueprint.get("/login")
def login_form():
    return render_template("auth/login.html")


@auth_blueprint.post("/login")
def login_submit():
    if not (username := request.form.get("username")):
        flash("Username is required", "error")
        return render_template("auth/login.html")

    if not (
        user := User.query.filter(User.username == username).one_or_none()
    ) or not check_password_hash(user.password, request.form.get("password")):
        flash("Invalid username or password", "error")
        return render_template("auth/login.html", username=username)

    _logger.info(
        f"Successful login from {request.remote_addr} by user '{user.username}'"
    )
    login_user(user, remember=True)
    return redirect(session.get("next") or url_for("root.index"))


@auth_blueprint.route("/logout")
def logout():
    logout_user()
    return redirect(url_for(".login_form"))

controllers/places.py
from logging import getLogger

from flask import Blueprint, render_template, abort, redirect, url_for, request, flash
from flask_login import current_user, login_required

from models import Place, LocationReport
from models.database import db

places_blueprint = Blueprint("places", __name__, url_prefix="/places")

_logger = getLogger(__name__)


@places_blueprint.get("/")
@login_required
def place_list():
    my_places = Place.query.filter(Place.user_id == current_user.id).order_by(Place.name)
    shared_places = Place.query.filter(Place.shared).order_by(Place.name)

    return render_template("places/list.html", my_places=my_places, shared_places=shared_places)


@places_blueprint.get("/<int:place_id>")
@login_required
def details(place_id: int):
    place = Place.query.get_or_404(place_id)

    if place.user_id != current_user.id and not place.shared:
        abort(403)

    return render_template("places/details.html", place=place)


@places_blueprint.post("/<int:place_id>")
@login_required
def edit(place_id: int):
    place = Place.query.get_or_404(place_id)

    if place.user_id != current_user.id and not place.shared:
        abort(403)

    if name := request.form.get("name"):
        place.name = name

    if address := request.form.get("address"):
        place.address = address

    place.shared = bool(request.form.get("shared"))

    db.session.commit()
    flash("Place updated successfully")

    return redirect(url_for(".details", place_id=place_id))


@places_blueprint.get("/<int:place_id>/delete")
@login_required
def confirm_delete(place_id: int):
    place = Place.query.get_or_404(place_id)

    if place.user_id != current_user.id and not place.shared:
        abort(403)

    return render_template(
        "places/delete.html",
        place=place,
        my_places=Place.query.filter(Place.id != place.id, Place.user_id == current_user.id).order_by(Place.name),
        shared_places=Place.query.filter(Place.id != place.id, Place.shared).order_by(Place.name),
    )


@places_blueprint.post("/<int:place_id>/delete")
@login_required
def delete(place_id: int):
    place = Place.query.get_or_404(place_id)

    if place.user_id != current_user.id and not place.shared:
        abort(403)

    if merge := request.form.get("merge", type=int):
        new_place = Place.query.get_or_404(merge)
        LocationReport.query.filter(LocationReport.place_id == place.id).update({"place_id": new_place.id})
        db.session.flush()

    db.session.delete(place)
    db.session.commit()
    flash("Place deleted successfully")
    return redirect(url_for(".place_list"))

controllers/root.py
from flask import Blueprint, redirect, url_for, render_template
from flask_login import login_required

root_blueprint = Blueprint("root", __name__)


@root_blueprint.get("/")
@login_required
def index():
    return render_template("home.html")


@root_blueprint.get("/map")
@login_required
def map_view():
    return render_template("map.html")

controllers/users.py
from logging import getLogger

from flask import (
    Blueprint,
    request,
    flash,
    redirect,
    render_template,
    url_for,
    make_response,
    send_from_directory,
    current_app,
    abort,
)
from flask_login import current_user, login_required
from werkzeug.security import generate_password_hash

from models import User
from models.database import db

users_blueprint = Blueprint("users", __name__, url_prefix="/users")

_logger = getLogger(__name__)


@users_blueprint.get("/")
@login_required
def user_list():
    return render_template("users/list.html", users=User.query.order_by(User.username))


@users_blueprint.post("/")
def manage_user():
    match request.form.get("action"):
        case "add":
            username = request.form.get("username").strip()
            password = request.form.get("password")
            db.session.add(User(username=username, password=password))
            db.session.commit()
            flash("User created successfully")
        case "delete":
            user_id = int(request.form.get("user_id"))

            if user_id == current_user.id:
                abort(403)

            User.query.filter(User.id == user_id).delete()
            db.session.commit()
            flash("User deleted successfully")

    return redirect(url_for(".user_list"))


@users_blueprint.get("/<username>/avatar")
@login_required
def avatar(username: str):
    if user := User.query.filter(
        User.username == username,
        User.avatar.is_not(None),
        User.avatar_type.is_not(None),
    ).one_or_none():
        response = make_response(user.avatar)
        response.content_type = user.avatar_type
        return response

    return send_from_directory(current_app.static_folder, "img/account.svg")


@users_blueprint.get("/me")
@login_required
def profile():
    return render_template("users/profile.html")


@users_blueprint.post("/me")
@login_required
def save_profile():
    user: User = current_user

    if username := request.form.get("username"):
        user.username = username

    if password := request.form.get("password"):
        user.password = generate_password_hash(password)

    if new_avatar := request.files.get("avatar"):
        user.avatar = new_avatar.stream.read()
        user.avatar_type = new_avatar.content_type
    elif request.form.get("action") == "clear_avatar":
        user.avatar = None

    if ha_instance := request.form.get("ha_instance"):
        user.ha_instance = ha_instance

    if ha_token := request.form.get("ha_token"):
        user.ha_token = ha_token

    if ha_entity := request.form.get("ha_entity"):
        user.ha_entity = ha_entity

    db.session.commit()
    flash("Changes saved successfully.")
    return redirect(url_for(".profile"))

templates/_base.html
<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>{% block title %}{% endblock %} | Traxor</title>
	<link rel="stylesheet" href="{{ url_for('static', filename='css/pico.min.css') }}">
	<link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap-grid.min.css') }}">
	<link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
	{% block head %}{% endblock %}
</head>
<body>
<nav class="container-fluid headerNav">
	<ul>
		<li><a href="/" class="contrast"><strong>Traxor</strong></a></li>

		{% if current_user.is_authenticated %}
			<li><a href="{{ url_for('root.map_view') }}">Map</a></li>
			<li><a href="{{ url_for('users.user_list') }}">Users</a></li>
			<li><a href="{{ url_for('places.place_list') }}">Places</a></li>
			<li><a href="{{ url_for('records.import_view') }}">Import</a></li>
		{% endif %}
	</ul>

	{% block nav %}{% endblock %}

	{% if current_user.is_authenticated %}
		<ul>
			<li>
				<details role="list" dir="rtl">
					<summary aria-haspopup="listbox" role="link">
						<img class="avatar" src="{{ url_for('users.avatar', username=current_user.username) }}"
						     alt="Avatar">
						{{ current_user.username }}
					</summary>
					<ul role="listbox">
						<li><a href="{{ url_for('users.profile') }}">Profile</a></li>
						<li><a href="{{ url_for('auth.logout') }}">Log out</a></li>
					</ul>
				</details>
			</li>
		</ul>
	{% endif %}
</nav>

{% with messages = get_flashed_messages(with_categories=True) %}
	{% if messages %}
		<section class="flashes container">
			{% for category, message in messages %}
				<article class="{{ category }}">{{ message }}</article>
			{% endfor %}
		</section>
	{% endif %}
{% endwith %}
{% block body %}{% endblock %}
</body>
</html>

templates/home.html
{% extends "_base.html" %}
{% block title %}Traxor{% endblock %}
{% block body %}
	<main class="container">

	</main>
{% endblock %}

templates/map.html
{% extends "_base.html" %}

{% block title %}Map{% endblock %}

{% block head %}
    <link rel="stylesheet" href="{{ url_for('static', filename='leaflet/leaflet.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/map.css') }}">
    <link id="RecordsURL" rel="x-records" href="{{ url_for('records.get_records') }}">
{% endblock %}

{% block nav %}
    <form class="row my-0" id="MapSettings">
        <div class="col py-1">
            <input type="datetime-local" name="start" class="mb-0" aria-label="Start">
        </div>
        <div class="col-auto pt-3">to</div>
        <div class="col py-1">
            <input type="datetime-local" name="end" class="mb-0" aria-label="End">
        </div>
        <div class="col py-1 d-flex align-items-end pb-1">
            <button type="submit" class="mb-0">Apply</button>
        </div>
    </form>
{% endblock %}

{% block body %}
    <div id="Map"></div>
    <script src="{{ url_for('static', filename='leaflet/leaflet.js') }}"></script>
    <script src="{{ url_for('static', filename='js/map.js') }}"></script>
{% endblock %}