models/user.py
from typing import Optional

from flask_login import UserMixin
from sqlalchemy.orm import relationship, mapped_column, Mapped

from models.database import db, CIText


class User(db.Model, UserMixin):
    __tablename__ = "users"

    # region columns

    id: Mapped[int] = mapped_column(primary_key=True)

    username: Mapped[str] = mapped_column(CIText, unique=True)

    password: Mapped[str]
    """Hashed password."""

    ha_instance: Mapped[Optional[str]]
    """Home Assistant instance URL."""

    ha_token: Mapped[Optional[str]]
    """Home Assistant long-lived access token."""

    ha_entity: Mapped[Optional[str]]
    """Home Assistant entity ID."""

    avatar: Mapped[Optional[bytes]]
    """Avatar image."""

    avatar_type: Mapped[Optional[str]]
    """Avatar image MIME type."""

    # endregion columns

    # region relationships

    location_reports = relationship(
        "LocationReport", back_populates="user", uselist=True, lazy="dynamic"
    )

    places = relationship("Place", back_populates="user", uselist=True, lazy="dynamic")

    # endregion relationships

    def __init__(self, *args, **kwargs):
        db.Model.__init__(self, *args, **kwargs)

controllers/owntracks.py
from datetime import datetime
from logging import getLogger

from flask import Blueprint, request, jsonify
from flask_login import current_user, login_required

from models import LocationReport
from models.database import db

owntracks_blueprint = Blueprint("owntracks", __name__, url_prefix="/ot")

_logger = getLogger(__name__)


@owntracks_blueprint.post("/")
@login_required
def report():
    location = LocationReport(
        user_id=current_user.id,
        timestamp=datetime.fromtimestamp(request.json.get("tst")),
        latitude=request.json.get("lat"),
        longitude=request.json.get("lon"),
        lat_lng_accuracy=request.json.get("acc"),
        altitude=request.json.get("alt"),
        alt_accuracy=request.json.get("vac"),
        source="OwnTracks",
    )

    db.session.add(location)
    db.session.commit()
    _logger.info(f"User '{current_user.username}' reported location via OwnTracks")
    return jsonify([])

controllers/users.py
from logging import getLogger

from flask import (
    Blueprint,
    request,
    flash,
    redirect,
    render_template,
    url_for,
    make_response,
    send_from_directory,
    current_app,
    abort,
)
from flask_login import current_user, login_required
from werkzeug.security import generate_password_hash

from models import User
from models.database import db

users_blueprint = Blueprint("users", __name__, url_prefix="/users")

_logger = getLogger(__name__)


@users_blueprint.get("/")
@login_required
def user_list():
    return render_template("users/list.html", users=User.query.order_by(User.username))


@users_blueprint.post("/")
def manage_user():
    match request.form.get("action"):
        case "add":
            username = request.form.get("username").strip()
            password = request.form.get("password")
            db.session.add(User(username=username, password=password))
            db.session.commit()
            flash("User created successfully")
        case "delete":
            user_id = int(request.form.get("user_id"))

            if user_id == current_user.id:
                abort(403)

            User.query.filter(User.id == user_id).delete()
            db.session.commit()
            flash("User deleted successfully")

    return redirect(url_for(".user_list"))


@users_blueprint.get("/<username>/avatar")
@login_required
def avatar(username: str):
    if user := User.query.filter(
        User.username == username,
        User.avatar.is_not(None),
        User.avatar_type.is_not(None),
    ).one_or_none():
        response = make_response(user.avatar)
        response.content_type = user.avatar_type
        return response

    return send_from_directory(current_app.static_folder, "img/account.svg")


@users_blueprint.get("/me")
@login_required
def profile():
    return render_template("users/profile.html")


@users_blueprint.post("/me")
@login_required
def save_profile():
    user: User = current_user

    if username := request.form.get("username"):
        user.username = username

    if password := request.form.get("password"):
        user.password = generate_password_hash(password)

    if new_avatar := request.files.get("avatar"):
        user.avatar = new_avatar.stream.read()
        user.avatar_type = new_avatar.content_type
    elif request.form.get("action") == "clear_avatar":
        user.avatar = None

    if ha_instance := request.form.get("ha_instance"):
        user.ha_instance = ha_instance

    if ha_token := request.form.get("ha_token"):
        user.ha_token = ha_token

    if ha_entity := request.form.get("ha_entity"):
        user.ha_entity = ha_entity

    db.session.commit()
    flash("Changes saved successfully.")
    return redirect(url_for(".profile"))

templates/users/list.html
{% extends "_base.html" %}
{% block title %}Users{% endblock %}
{% block body %}
    <main class="container">
        <article>
            <header>Users</header>

            <table class="usersTable">
                <thead>
                <tr>
                    <th scope="row">ID</th>
                    <th scope="row" style="text-align: center;">Avatar</th>
                    <th scope="row">Username</th>
                    <th scope="row">Location reports</th>
                    <th scope="row">Places</th>
                    <th scope="row">Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for user in users %}
                    <tr>
                        <td>{{ user.id }}</td>
                        <td style="text-align: center;">
                            <img src="{{ url_for('users.avatar', username=user.username) }}"
                                 alt="{{ user.username }}'s avatar" class="avatar"/>
                        </td>
                        <td>{{ user.username }}</td>
                        <td>{{ "{:,}".format(user.location_reports.count()) }}</td>
                        <td>{{ "{:,}".format(user.places.count()) }}</td>
                        <td>
                            {% if user.id != current_user.id %}
                                <form action="" method="POST">
                                    <input type="hidden" name="user_id" value="{{ user.id }}">
                                    <button type="submit" name="action" value="delete" class="outline secondary"
                                            onclick="return confirm('Are you sure you want to delete {{ user.username }} and all of their location history?')">
                                        Delete
                                    </button>
                                </form>
                            {% endif %}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </article>

        <article>
            <header>Add user</header>

            <form action="" method="POST">
                <label>
                    Username
                    <input type="text" name="username" value="{{ current_user.username }}" required autocomplete="off">
                </label>

                <label>
                    Password
                    <input type="password" name="password" required autocomplete="new-password">
                </label>

                <button type="submit" name="action" value="add">Add</button>
            </form>
        </article>
    </main>
{% endblock %}

templates/users/profile.html
{% extends "_base.html" %}
{% block title %}Profile{% endblock %}
{% block body %}
	<main class="container">
		<article>
			<div class="row">
				<div class="col-sm-5">
					<form action="" method="POST" enctype="multipart/form-data">
						<label>
							<img src="{{ url_for('.avatar', username=current_user.username) }}" alt="Avatar">
							<input type="file" name="avatar">
						</label>
						<button type="submit">Upload</button>
						{% if current_user.avatar %}
							<button type="submit" class="secondary" name="action" value="clear_avatar">Clear</button>
						{% endif %}
					</form>
				</div>
				<div class="col-sm-7">
					<form action="" method="POST">
						<label>
							Username
							<input type="text" name="username" value="{{ current_user.username }}" required>
						</label>

						<label>
							New password
							<input type="password" name="password" placeholder="(unchanged)">
						</label>

						<button type="submit">Save</button>
					</form>
				</div>
			</div>
		</article>

		<article id="hass">
			<header>Home Assistant</header>

			<form action="" method="POST">
				<label>
					Instance URL
					<input type="url" name="ha_instance" value="{{ current_user.ha_instance or "" }}" required
						   placeholder="http://homeassistant.local:8123">
				</label>

				<label>
					Long-lived access token
					<input type="password" name="ha_token"
						   placeholder="{% if current_user.ha_token %}(unchanged){% endif %}">
				</label>

				<label>
					Entity ID
					<input type="text" name="ha_entity" value="{{ current_user.ha_entity or "" }}"
						   placeholder="device_tracker.your_phone" required>
				</label>

				<button type="submit">Save</button>
			</form>
		</article>

		<article>
			<header>OwnTracks</header>

			<p><b>Mode:</b> HTTP</p>
			<p><b>Host:</b>
				<mark>{{ url_for('owntracks.report', _external=True) }}</mark>
			</p>
			<p><b>Username:</b>
				<mark>{{ current_user.username }}</mark>
			</p>
			<p><b>Password:</b> [your password]</p>
		</article>
	</main>
{% endblock %}